"use strict";

const fs = require("fs");
const path = require("path");
const palette = require("../../assets-src/pixel/palette.js");
const ui = require("../../assets-src/pixel/ui-assets.js");
const battle = require("../../assets-src/pixel/battle-assets.js");
const effects = require("../../assets-src/pixel/effect-assets.js");
const catalog = require("../../assets-src/pixel/catalog-assets.js");
const { PixelCanvas, sha256 } = require("./lib.js");

const ROOT = path.resolve(__dirname, "../..");
const OUTPUT = path.join(ROOT, "public/assets/pixel");

function generateOutputs() {
  const seen = new Set();
  const sprites = {};
  const atlasOutputs = {};
  const atlases = {};
  for (const recipe of [ui, battle, effects, ...catalog.recipes]) {
    const canvas = new PixelCanvas(recipe.atlas.width, recipe.atlas.height);
    const recipeSpriteNames = [];
    for (const sprite of recipe.sprites) {
      if (seen.has(sprite.name)) throw new Error(`Duplicate sprite name: ${sprite.name}`);
      seen.add(sprite.name);
      if (sprite.x < 0 || sprite.y < 0 || sprite.x + sprite.width > canvas.width || sprite.y + sprite.height > canvas.height) throw new Error(`Sprite exceeds atlas: ${sprite.name}`);
      sprite.draw(canvas, sprite.x, sprite.y);
      sprites[sprite.name] = { atlas: recipe.atlas.name, x: sprite.x, y: sprite.y, width: sprite.width, height: sprite.height };
      recipeSpriteNames.push(sprite.name);
    }
    for (const name of recipeSpriteNames) {
      const sprite = sprites[name];
      const region = canvas.regionData(sprite.x, sprite.y, sprite.width, sprite.height);
      let opaquePixels = 0;
      for (let alpha = 3; alpha < region.length; alpha += 4) {
        if (region[alpha] !== 0) opaquePixels += 1;
      }
      sprite.sha256 = sha256(region);
      sprite.opaquePixels = opaquePixels;
    }
    const png = canvas.encodePng();
    const file = `${recipe.atlas.name}-atlas.png`;
    atlasOutputs[file] = png;
    atlases[recipe.atlas.name] = { file, width: canvas.width, height: canvas.height, bytes: png.length, sha256: sha256(png), critical: recipe.atlas.critical !== false };
  }
  const rules = Object.entries(sprites).map(([name, sprite]) => `.pixel-${name} { width:${sprite.width}px; height:${sprite.height}px; background-image:url("/assets/pixel/${atlases[sprite.atlas].file}"); background-position:-${sprite.x}px -${sprite.y}px; }`).join("\n");
  const css = `/* Generated by npm run assets:generate. Do not edit. */\n.pixel-sprite { display:inline-block; flex:0 0 auto; background-repeat:no-repeat; image-rendering:pixelated; }\n${rules}\n`;
  const manifest = {
    version: 1,
    generatedBy: "scripts/pixel-art/generate.js",
    logicalScale: 1,
    palette,
    atlases,
    sprites
  };
  return {
    ...atlasOutputs,
    "pixel-art.css": Buffer.from(css, "utf8"),
    "manifest.json": Buffer.from(`${JSON.stringify(manifest, null, 2)}\n`, "utf8")
  };
}

function writeOutputs(outputs = generateOutputs()) {
  fs.mkdirSync(OUTPUT, { recursive: true });
  for (const [name, contents] of Object.entries(outputs)) fs.writeFileSync(path.join(OUTPUT, name), contents);
}

if (require.main === module) {
  writeOutputs();
  process.stdout.write(`Generated ${Object.keys(generateOutputs()).length} pixel-art files in ${path.relative(ROOT, OUTPUT)}.\n`);
}

module.exports = { OUTPUT, generateOutputs, writeOutputs };
